/*
   Contributer : github.com/jaswal72
   Email : shubhamjaswal772@gmail.com
*/
SELECT IF(STUDENTS.Marks < 70, 'NULL',STUDENTS.NAME) , GRADES.GRADE, STUDENTS.MARKS
 FROM STUDENTS, GRADES WHERE STUDENTS.MARKS BETWEEN MIN_MARK AND MAX_MARK
 ORDER BY GRADES.GRADE DESC, STUDENTS.NAME; 
